
services:

  miner:
    container_name: miner
    image: yur0n/twitch-miner
    build:
      context: ./miner
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 5001:5001
    environment:
      - WEBHOOK_ENDPOINT=http://backend:5000/webhook
      - NODE_ENV=production
      - PORT=5001
      - TERM=xterm-256color
    depends_on:
      - backend

  frontend:
    container_name: frontend
    image: yur0n/twitch-frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - backend

  backend:
    container_name: backend
    image: yur0n/twitch-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - MINER_ENDPOINT=http://miner:5001
      - NODE_ENV=production
      - PORT=5000
      - DB_URL=mongodb://mongo:27017/main
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=main
    volumes:
      - pgdata:/data/db

volumes:
  pgdata:
    driver: local